-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity custom2 is
port (
    clock1 : IN STD_LOGIC;
    clock2 : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    enable : IN STD_LOGIC;
    out_counter1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_counter2 : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of custom2 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "custom2,hls_ip_2018_3,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.797000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=20,HLS_SYN_LUT=42,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal grp_first_counter_fu_70_out_counter : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_first_counter_fu_86_out_counter : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";

    component first_counter IS
    port (
        enable : IN STD_LOGIC;
        out_counter : OUT STD_LOGIC_VECTOR (3 downto 0);
        clock : IN STD_LOGIC;
        reset : IN STD_LOGIC );
    end component;



begin
    grp_first_counter_fu_70 : component first_counter
    port map (
        enable => enable,
        out_counter => grp_first_counter_fu_70_out_counter,
        clock => clock1,
        reset => reset);

    grp_first_counter_fu_86 : component first_counter
    port map (
        enable => enable,
        out_counter => grp_first_counter_fu_86_out_counter,
        clock => clock2,
        reset => reset);




    ap_CS_fsm <= ap_const_lv2_0;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    out_counter1 <= grp_first_counter_fu_70_out_counter;
    out_counter2 <= grp_first_counter_fu_86_out_counter;
end behav;
