-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity datag is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    din_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    din_TVALID : OUT STD_LOGIC;
    din_TREADY : IN STD_LOGIC;
    din_TLAST : OUT STD_LOGIC;
    control_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    control_V_TVALID : OUT STD_LOGIC;
    control_V_TREADY : IN STD_LOGIC;
    din_words_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    din_words_TVALID : OUT STD_LOGIC;
    din_words_TREADY : IN STD_LOGIC;
    din_words_TLAST : OUT STD_LOGIC;
    dout_words_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    dout_words_TVALID : OUT STD_LOGIC;
    dout_words_TREADY : IN STD_LOGIC;
    dout_words_TLAST : OUT STD_LOGIC );
end;


architecture behav of datag is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "datag,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu28dr-ffvg1517-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=23,HLS_SYN_LUT=160,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_FC558F04 : STD_LOGIC_VECTOR (31 downto 0) := "11111100010101011000111100000100";
    constant ap_const_lv8_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000101";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000001110100101011110111010000001100110100111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal din_V_data_V_1_data_out : STD_LOGIC_VECTOR (127 downto 0);
    signal din_V_data_V_1_vld_in : STD_LOGIC;
    signal din_V_data_V_1_vld_out : STD_LOGIC;
    signal din_V_data_V_1_ack_in : STD_LOGIC;
    signal din_V_data_V_1_ack_out : STD_LOGIC;
    signal din_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal din_V_data_V_1_sel : STD_LOGIC;
    signal din_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal din_V_tlast_1_data_out : STD_LOGIC;
    signal din_V_tlast_1_vld_in : STD_LOGIC;
    signal din_V_tlast_1_vld_out : STD_LOGIC;
    signal din_V_tlast_1_ack_in : STD_LOGIC;
    signal din_V_tlast_1_ack_out : STD_LOGIC;
    signal din_V_tlast_1_sel_rd : STD_LOGIC := '0';
    signal din_V_tlast_1_sel : STD_LOGIC;
    signal din_V_tlast_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal control_V_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal control_V_1_vld_in : STD_LOGIC;
    signal control_V_1_vld_out : STD_LOGIC;
    signal control_V_1_ack_in : STD_LOGIC;
    signal control_V_1_ack_out : STD_LOGIC;
    signal control_V_1_sel_rd : STD_LOGIC := '0';
    signal control_V_1_sel : STD_LOGIC;
    signal control_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal din_words_V_data_V_1_data_out : STD_LOGIC_VECTOR (7 downto 0);
    signal din_words_V_data_V_1_vld_in : STD_LOGIC;
    signal din_words_V_data_V_1_vld_out : STD_LOGIC;
    signal din_words_V_data_V_1_ack_in : STD_LOGIC;
    signal din_words_V_data_V_1_ack_out : STD_LOGIC;
    signal din_words_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal din_words_V_data_V_1_sel : STD_LOGIC;
    signal din_words_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal din_words_V_tlast_1_data_out : STD_LOGIC;
    signal din_words_V_tlast_1_vld_in : STD_LOGIC;
    signal din_words_V_tlast_1_vld_out : STD_LOGIC;
    signal din_words_V_tlast_1_ack_in : STD_LOGIC;
    signal din_words_V_tlast_1_ack_out : STD_LOGIC;
    signal din_words_V_tlast_1_sel_rd : STD_LOGIC := '0';
    signal din_words_V_tlast_1_sel : STD_LOGIC;
    signal din_words_V_tlast_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal dout_words_V_data_V_1_data_out : STD_LOGIC_VECTOR (7 downto 0);
    signal dout_words_V_data_V_1_vld_in : STD_LOGIC;
    signal dout_words_V_data_V_1_vld_out : STD_LOGIC;
    signal dout_words_V_data_V_1_ack_in : STD_LOGIC;
    signal dout_words_V_data_V_1_ack_out : STD_LOGIC;
    signal dout_words_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal dout_words_V_data_V_1_sel : STD_LOGIC;
    signal dout_words_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal dout_words_V_tlast_1_data_out : STD_LOGIC;
    signal dout_words_V_tlast_1_vld_in : STD_LOGIC;
    signal dout_words_V_tlast_1_vld_out : STD_LOGIC;
    signal dout_words_V_tlast_1_ack_in : STD_LOGIC;
    signal dout_words_V_tlast_1_ack_out : STD_LOGIC;
    signal dout_words_V_tlast_1_sel_rd : STD_LOGIC := '0';
    signal dout_words_V_tlast_1_sel : STD_LOGIC;
    signal dout_words_V_tlast_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal din_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal control_V_TDATA_blk_n : STD_LOGIC;
    signal din_words_TDATA_blk_n : STD_LOGIC;
    signal dout_words_TDATA_blk_n : STD_LOGIC;
    signal ap_block_state1_io : BOOLEAN;
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    control_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                control_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((control_V_1_ack_out = ap_const_logic_1) and (control_V_1_vld_out = ap_const_logic_1))) then 
                                        control_V_1_sel_rd <= not(control_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    control_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                control_V_1_state <= ap_const_lv2_0;
            else
                if ((((control_V_1_state = ap_const_lv2_2) and (control_V_1_vld_in = ap_const_logic_0)) or ((control_V_1_state = ap_const_lv2_3) and (control_V_1_vld_in = ap_const_logic_0) and (control_V_1_ack_out = ap_const_logic_1)))) then 
                    control_V_1_state <= ap_const_lv2_2;
                elsif ((((control_V_1_state = ap_const_lv2_1) and (control_V_1_ack_out = ap_const_logic_0)) or ((control_V_1_state = ap_const_lv2_3) and (control_V_1_ack_out = ap_const_logic_0) and (control_V_1_vld_in = ap_const_logic_1)))) then 
                    control_V_1_state <= ap_const_lv2_1;
                elsif (((not(((control_V_1_vld_in = ap_const_logic_0) and (control_V_1_ack_out = ap_const_logic_1))) and not(((control_V_1_ack_out = ap_const_logic_0) and (control_V_1_vld_in = ap_const_logic_1))) and (control_V_1_state = ap_const_lv2_3)) or ((control_V_1_state = ap_const_lv2_1) and (control_V_1_ack_out = ap_const_logic_1)) or ((control_V_1_state = ap_const_lv2_2) and (control_V_1_vld_in = ap_const_logic_1)))) then 
                    control_V_1_state <= ap_const_lv2_3;
                else 
                    control_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    din_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                din_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((din_V_data_V_1_ack_out = ap_const_logic_1) and (din_V_data_V_1_vld_out = ap_const_logic_1))) then 
                                        din_V_data_V_1_sel_rd <= not(din_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    din_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                din_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((din_V_data_V_1_state = ap_const_lv2_2) and (din_V_data_V_1_vld_in = ap_const_logic_0)) or ((din_V_data_V_1_state = ap_const_lv2_3) and (din_V_data_V_1_vld_in = ap_const_logic_0) and (din_V_data_V_1_ack_out = ap_const_logic_1)))) then 
                    din_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((din_V_data_V_1_state = ap_const_lv2_1) and (din_V_data_V_1_ack_out = ap_const_logic_0)) or ((din_V_data_V_1_state = ap_const_lv2_3) and (din_V_data_V_1_ack_out = ap_const_logic_0) and (din_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    din_V_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((din_V_data_V_1_vld_in = ap_const_logic_0) and (din_V_data_V_1_ack_out = ap_const_logic_1))) and not(((din_V_data_V_1_ack_out = ap_const_logic_0) and (din_V_data_V_1_vld_in = ap_const_logic_1))) and (din_V_data_V_1_state = ap_const_lv2_3)) or ((din_V_data_V_1_state = ap_const_lv2_1) and (din_V_data_V_1_ack_out = ap_const_logic_1)) or ((din_V_data_V_1_state = ap_const_lv2_2) and (din_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    din_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    din_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    din_V_tlast_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                din_V_tlast_1_sel_rd <= ap_const_logic_0;
            else
                if (((din_V_tlast_1_ack_out = ap_const_logic_1) and (din_V_tlast_1_vld_out = ap_const_logic_1))) then 
                                        din_V_tlast_1_sel_rd <= not(din_V_tlast_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    din_V_tlast_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                din_V_tlast_1_state <= ap_const_lv2_0;
            else
                if ((((din_V_tlast_1_state = ap_const_lv2_2) and (din_V_tlast_1_vld_in = ap_const_logic_0)) or ((din_V_tlast_1_state = ap_const_lv2_3) and (din_V_tlast_1_vld_in = ap_const_logic_0) and (din_V_tlast_1_ack_out = ap_const_logic_1)))) then 
                    din_V_tlast_1_state <= ap_const_lv2_2;
                elsif ((((din_V_tlast_1_state = ap_const_lv2_1) and (din_V_tlast_1_ack_out = ap_const_logic_0)) or ((din_V_tlast_1_state = ap_const_lv2_3) and (din_V_tlast_1_ack_out = ap_const_logic_0) and (din_V_tlast_1_vld_in = ap_const_logic_1)))) then 
                    din_V_tlast_1_state <= ap_const_lv2_1;
                elsif (((not(((din_V_tlast_1_vld_in = ap_const_logic_0) and (din_V_tlast_1_ack_out = ap_const_logic_1))) and not(((din_V_tlast_1_ack_out = ap_const_logic_0) and (din_V_tlast_1_vld_in = ap_const_logic_1))) and (din_V_tlast_1_state = ap_const_lv2_3)) or ((din_V_tlast_1_state = ap_const_lv2_1) and (din_V_tlast_1_ack_out = ap_const_logic_1)) or ((din_V_tlast_1_state = ap_const_lv2_2) and (din_V_tlast_1_vld_in = ap_const_logic_1)))) then 
                    din_V_tlast_1_state <= ap_const_lv2_3;
                else 
                    din_V_tlast_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    din_words_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                din_words_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((din_words_V_data_V_1_ack_out = ap_const_logic_1) and (din_words_V_data_V_1_vld_out = ap_const_logic_1))) then 
                                        din_words_V_data_V_1_sel_rd <= not(din_words_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    din_words_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                din_words_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((din_words_V_data_V_1_state = ap_const_lv2_2) and (din_words_V_data_V_1_vld_in = ap_const_logic_0)) or ((din_words_V_data_V_1_state = ap_const_lv2_3) and (din_words_V_data_V_1_vld_in = ap_const_logic_0) and (din_words_V_data_V_1_ack_out = ap_const_logic_1)))) then 
                    din_words_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((din_words_V_data_V_1_state = ap_const_lv2_1) and (din_words_V_data_V_1_ack_out = ap_const_logic_0)) or ((din_words_V_data_V_1_state = ap_const_lv2_3) and (din_words_V_data_V_1_ack_out = ap_const_logic_0) and (din_words_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    din_words_V_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((din_words_V_data_V_1_vld_in = ap_const_logic_0) and (din_words_V_data_V_1_ack_out = ap_const_logic_1))) and not(((din_words_V_data_V_1_ack_out = ap_const_logic_0) and (din_words_V_data_V_1_vld_in = ap_const_logic_1))) and (din_words_V_data_V_1_state = ap_const_lv2_3)) or ((din_words_V_data_V_1_state = ap_const_lv2_1) and (din_words_V_data_V_1_ack_out = ap_const_logic_1)) or ((din_words_V_data_V_1_state = ap_const_lv2_2) and (din_words_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    din_words_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    din_words_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    din_words_V_tlast_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                din_words_V_tlast_1_sel_rd <= ap_const_logic_0;
            else
                if (((din_words_V_tlast_1_ack_out = ap_const_logic_1) and (din_words_V_tlast_1_vld_out = ap_const_logic_1))) then 
                                        din_words_V_tlast_1_sel_rd <= not(din_words_V_tlast_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    din_words_V_tlast_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                din_words_V_tlast_1_state <= ap_const_lv2_0;
            else
                if ((((din_words_V_tlast_1_state = ap_const_lv2_2) and (din_words_V_tlast_1_vld_in = ap_const_logic_0)) or ((din_words_V_tlast_1_state = ap_const_lv2_3) and (din_words_V_tlast_1_vld_in = ap_const_logic_0) and (din_words_V_tlast_1_ack_out = ap_const_logic_1)))) then 
                    din_words_V_tlast_1_state <= ap_const_lv2_2;
                elsif ((((din_words_V_tlast_1_state = ap_const_lv2_1) and (din_words_V_tlast_1_ack_out = ap_const_logic_0)) or ((din_words_V_tlast_1_state = ap_const_lv2_3) and (din_words_V_tlast_1_ack_out = ap_const_logic_0) and (din_words_V_tlast_1_vld_in = ap_const_logic_1)))) then 
                    din_words_V_tlast_1_state <= ap_const_lv2_1;
                elsif (((not(((din_words_V_tlast_1_vld_in = ap_const_logic_0) and (din_words_V_tlast_1_ack_out = ap_const_logic_1))) and not(((din_words_V_tlast_1_ack_out = ap_const_logic_0) and (din_words_V_tlast_1_vld_in = ap_const_logic_1))) and (din_words_V_tlast_1_state = ap_const_lv2_3)) or ((din_words_V_tlast_1_state = ap_const_lv2_1) and (din_words_V_tlast_1_ack_out = ap_const_logic_1)) or ((din_words_V_tlast_1_state = ap_const_lv2_2) and (din_words_V_tlast_1_vld_in = ap_const_logic_1)))) then 
                    din_words_V_tlast_1_state <= ap_const_lv2_3;
                else 
                    din_words_V_tlast_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    dout_words_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dout_words_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((dout_words_V_data_V_1_ack_out = ap_const_logic_1) and (dout_words_V_data_V_1_vld_out = ap_const_logic_1))) then 
                                        dout_words_V_data_V_1_sel_rd <= not(dout_words_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    dout_words_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dout_words_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((dout_words_V_data_V_1_state = ap_const_lv2_2) and (dout_words_V_data_V_1_vld_in = ap_const_logic_0)) or ((dout_words_V_data_V_1_state = ap_const_lv2_3) and (dout_words_V_data_V_1_vld_in = ap_const_logic_0) and (dout_words_V_data_V_1_ack_out = ap_const_logic_1)))) then 
                    dout_words_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((dout_words_V_data_V_1_state = ap_const_lv2_1) and (dout_words_V_data_V_1_ack_out = ap_const_logic_0)) or ((dout_words_V_data_V_1_state = ap_const_lv2_3) and (dout_words_V_data_V_1_ack_out = ap_const_logic_0) and (dout_words_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    dout_words_V_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((dout_words_V_data_V_1_vld_in = ap_const_logic_0) and (dout_words_V_data_V_1_ack_out = ap_const_logic_1))) and not(((dout_words_V_data_V_1_ack_out = ap_const_logic_0) and (dout_words_V_data_V_1_vld_in = ap_const_logic_1))) and (dout_words_V_data_V_1_state = ap_const_lv2_3)) or ((dout_words_V_data_V_1_state = ap_const_lv2_1) and (dout_words_V_data_V_1_ack_out = ap_const_logic_1)) or ((dout_words_V_data_V_1_state = ap_const_lv2_2) and (dout_words_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    dout_words_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    dout_words_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    dout_words_V_tlast_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dout_words_V_tlast_1_sel_rd <= ap_const_logic_0;
            else
                if (((dout_words_V_tlast_1_ack_out = ap_const_logic_1) and (dout_words_V_tlast_1_vld_out = ap_const_logic_1))) then 
                                        dout_words_V_tlast_1_sel_rd <= not(dout_words_V_tlast_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    dout_words_V_tlast_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dout_words_V_tlast_1_state <= ap_const_lv2_0;
            else
                if ((((dout_words_V_tlast_1_state = ap_const_lv2_2) and (dout_words_V_tlast_1_vld_in = ap_const_logic_0)) or ((dout_words_V_tlast_1_state = ap_const_lv2_3) and (dout_words_V_tlast_1_vld_in = ap_const_logic_0) and (dout_words_V_tlast_1_ack_out = ap_const_logic_1)))) then 
                    dout_words_V_tlast_1_state <= ap_const_lv2_2;
                elsif ((((dout_words_V_tlast_1_state = ap_const_lv2_1) and (dout_words_V_tlast_1_ack_out = ap_const_logic_0)) or ((dout_words_V_tlast_1_state = ap_const_lv2_3) and (dout_words_V_tlast_1_ack_out = ap_const_logic_0) and (dout_words_V_tlast_1_vld_in = ap_const_logic_1)))) then 
                    dout_words_V_tlast_1_state <= ap_const_lv2_1;
                elsif (((not(((dout_words_V_tlast_1_vld_in = ap_const_logic_0) and (dout_words_V_tlast_1_ack_out = ap_const_logic_1))) and not(((dout_words_V_tlast_1_ack_out = ap_const_logic_0) and (dout_words_V_tlast_1_vld_in = ap_const_logic_1))) and (dout_words_V_tlast_1_state = ap_const_lv2_3)) or ((dout_words_V_tlast_1_state = ap_const_lv2_1) and (dout_words_V_tlast_1_ack_out = ap_const_logic_1)) or ((dout_words_V_tlast_1_state = ap_const_lv2_2) and (dout_words_V_tlast_1_vld_in = ap_const_logic_1)))) then 
                    dout_words_V_tlast_1_state <= ap_const_lv2_3;
                else 
                    dout_words_V_tlast_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, din_V_data_V_1_ack_in, din_V_data_V_1_state, din_V_tlast_1_ack_in, din_V_tlast_1_state, control_V_1_ack_in, control_V_1_state, din_words_V_data_V_1_ack_in, din_words_V_data_V_1_state, din_words_V_tlast_1_ack_in, din_words_V_tlast_1_state, dout_words_V_data_V_1_ack_in, dout_words_V_data_V_1_state, dout_words_V_tlast_1_ack_in, dout_words_V_tlast_1_state, ap_CS_fsm_state2, ap_block_state1_io, ap_block_state2_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((din_V_tlast_1_ack_in = ap_const_logic_0) or (dout_words_V_tlast_1_ack_in = ap_const_logic_0) or (dout_words_V_data_V_1_ack_in = ap_const_logic_0) or (din_V_data_V_1_ack_in = ap_const_logic_0) or (din_words_V_tlast_1_ack_in = ap_const_logic_0) or (din_words_V_data_V_1_ack_in = ap_const_logic_0) or (control_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io))) and (din_V_data_V_1_state(0) = ap_const_logic_0) and (dout_words_V_tlast_1_state(0) = ap_const_logic_0) and (dout_words_V_data_V_1_state(0) = ap_const_logic_0) and (din_words_V_tlast_1_state(0) = ap_const_logic_0) and (din_words_V_data_V_1_state(0) = ap_const_logic_0) and (control_V_1_state(0) = ap_const_logic_0) and (din_V_tlast_1_state(0) = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state1_io_assign_proc : process(din_V_data_V_1_ack_in, control_V_1_ack_in, din_words_V_data_V_1_ack_in, dout_words_V_data_V_1_ack_in)
    begin
                ap_block_state1_io <= ((dout_words_V_data_V_1_ack_in = ap_const_logic_0) or (din_V_data_V_1_ack_in = ap_const_logic_0) or (din_words_V_data_V_1_ack_in = ap_const_logic_0) or (control_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(din_V_data_V_1_ack_in, din_V_tlast_1_ack_in, control_V_1_ack_in, din_words_V_data_V_1_ack_in, din_words_V_tlast_1_ack_in, dout_words_V_data_V_1_ack_in, dout_words_V_tlast_1_ack_in)
    begin
                ap_block_state2 <= ((din_V_tlast_1_ack_in = ap_const_logic_0) or (dout_words_V_tlast_1_ack_in = ap_const_logic_0) or (dout_words_V_data_V_1_ack_in = ap_const_logic_0) or (din_V_data_V_1_ack_in = ap_const_logic_0) or (din_words_V_tlast_1_ack_in = ap_const_logic_0) or (din_words_V_data_V_1_ack_in = ap_const_logic_0) or (control_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_block_state2_io_assign_proc : process(din_V_data_V_1_ack_in, control_V_1_ack_in, din_words_V_data_V_1_ack_in, dout_words_V_data_V_1_ack_in)
    begin
                ap_block_state2_io <= ((dout_words_V_data_V_1_ack_in = ap_const_logic_0) or (din_V_data_V_1_ack_in = ap_const_logic_0) or (din_words_V_data_V_1_ack_in = ap_const_logic_0) or (control_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(din_V_data_V_1_ack_in, din_V_data_V_1_state, din_V_tlast_1_ack_in, din_V_tlast_1_state, control_V_1_ack_in, control_V_1_state, din_words_V_data_V_1_ack_in, din_words_V_data_V_1_state, din_words_V_tlast_1_ack_in, din_words_V_tlast_1_state, dout_words_V_data_V_1_ack_in, dout_words_V_data_V_1_state, dout_words_V_tlast_1_ack_in, dout_words_V_tlast_1_state, ap_CS_fsm_state2, ap_block_state2_io)
    begin
        if ((not(((din_V_tlast_1_ack_in = ap_const_logic_0) or (dout_words_V_tlast_1_ack_in = ap_const_logic_0) or (dout_words_V_data_V_1_ack_in = ap_const_logic_0) or (din_V_data_V_1_ack_in = ap_const_logic_0) or (din_words_V_tlast_1_ack_in = ap_const_logic_0) or (din_words_V_data_V_1_ack_in = ap_const_logic_0) or (control_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io))) and (din_V_data_V_1_state(0) = ap_const_logic_0) and (dout_words_V_tlast_1_state(0) = ap_const_logic_0) and (dout_words_V_data_V_1_state(0) = ap_const_logic_0) and (din_words_V_tlast_1_state(0) = ap_const_logic_0) and (din_words_V_data_V_1_state(0) = ap_const_logic_0) and (control_V_1_state(0) = ap_const_logic_0) and (din_V_tlast_1_state(0) = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(din_V_data_V_1_ack_in, din_V_data_V_1_state, din_V_tlast_1_ack_in, din_V_tlast_1_state, control_V_1_ack_in, control_V_1_state, din_words_V_data_V_1_ack_in, din_words_V_data_V_1_state, din_words_V_tlast_1_ack_in, din_words_V_tlast_1_state, dout_words_V_data_V_1_ack_in, dout_words_V_data_V_1_state, dout_words_V_tlast_1_ack_in, dout_words_V_tlast_1_state, ap_CS_fsm_state2, ap_block_state2_io)
    begin
        if ((not(((din_V_tlast_1_ack_in = ap_const_logic_0) or (dout_words_V_tlast_1_ack_in = ap_const_logic_0) or (dout_words_V_data_V_1_ack_in = ap_const_logic_0) or (din_V_data_V_1_ack_in = ap_const_logic_0) or (din_words_V_tlast_1_ack_in = ap_const_logic_0) or (din_words_V_data_V_1_ack_in = ap_const_logic_0) or (control_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io))) and (din_V_data_V_1_state(0) = ap_const_logic_0) and (dout_words_V_tlast_1_state(0) = ap_const_logic_0) and (dout_words_V_data_V_1_state(0) = ap_const_logic_0) and (din_words_V_tlast_1_state(0) = ap_const_logic_0) and (din_words_V_data_V_1_state(0) = ap_const_logic_0) and (control_V_1_state(0) = ap_const_logic_0) and (din_V_tlast_1_state(0) = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    control_V_1_ack_in <= control_V_1_state(1);
    control_V_1_ack_out <= control_V_TREADY;
    control_V_1_data_out <= ap_const_lv32_FC558F04;
    control_V_1_sel <= control_V_1_sel_rd;

    control_V_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            control_V_1_vld_in <= ap_const_logic_1;
        else 
            control_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    control_V_1_vld_out <= control_V_1_state(0);
    control_V_TDATA <= control_V_1_data_out;

    control_V_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, control_V_1_state, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            control_V_TDATA_blk_n <= control_V_1_state(1);
        else 
            control_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    control_V_TVALID <= control_V_1_state(0);
    din_TDATA <= din_V_data_V_1_data_out;

    din_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, din_V_data_V_1_state, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            din_TDATA_blk_n <= din_V_data_V_1_state(1);
        else 
            din_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_TLAST <= din_V_tlast_1_data_out;
    din_TVALID <= din_V_tlast_1_state(0);
    din_V_data_V_1_ack_in <= din_V_data_V_1_state(1);
    din_V_data_V_1_ack_out <= din_TREADY;
    din_V_data_V_1_data_out <= ap_const_lv128_lc_1;
    din_V_data_V_1_sel <= din_V_data_V_1_sel_rd;

    din_V_data_V_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            din_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            din_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    din_V_data_V_1_vld_out <= din_V_data_V_1_state(0);
    din_V_tlast_1_ack_in <= din_V_tlast_1_state(1);
    din_V_tlast_1_ack_out <= din_TREADY;
    din_V_tlast_1_data_out <= ap_const_logic_1;
    din_V_tlast_1_sel <= din_V_tlast_1_sel_rd;

    din_V_tlast_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            din_V_tlast_1_vld_in <= ap_const_logic_1;
        else 
            din_V_tlast_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    din_V_tlast_1_vld_out <= din_V_tlast_1_state(0);
    din_words_TDATA <= din_words_V_data_V_1_data_out;

    din_words_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, din_words_V_data_V_1_state, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            din_words_TDATA_blk_n <= din_words_V_data_V_1_state(1);
        else 
            din_words_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_words_TLAST <= din_words_V_tlast_1_data_out;
    din_words_TVALID <= din_words_V_tlast_1_state(0);
    din_words_V_data_V_1_ack_in <= din_words_V_data_V_1_state(1);
    din_words_V_data_V_1_ack_out <= din_words_TREADY;
    din_words_V_data_V_1_data_out <= ap_const_lv8_5;
    din_words_V_data_V_1_sel <= din_words_V_data_V_1_sel_rd;

    din_words_V_data_V_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            din_words_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            din_words_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    din_words_V_data_V_1_vld_out <= din_words_V_data_V_1_state(0);
    din_words_V_tlast_1_ack_in <= din_words_V_tlast_1_state(1);
    din_words_V_tlast_1_ack_out <= din_words_TREADY;
    din_words_V_tlast_1_data_out <= ap_const_logic_1;
    din_words_V_tlast_1_sel <= din_words_V_tlast_1_sel_rd;

    din_words_V_tlast_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            din_words_V_tlast_1_vld_in <= ap_const_logic_1;
        else 
            din_words_V_tlast_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    din_words_V_tlast_1_vld_out <= din_words_V_tlast_1_state(0);
    dout_words_TDATA <= dout_words_V_data_V_1_data_out;

    dout_words_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, dout_words_V_data_V_1_state, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            dout_words_TDATA_blk_n <= dout_words_V_data_V_1_state(1);
        else 
            dout_words_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dout_words_TLAST <= dout_words_V_tlast_1_data_out;
    dout_words_TVALID <= dout_words_V_tlast_1_state(0);
    dout_words_V_data_V_1_ack_in <= dout_words_V_data_V_1_state(1);
    dout_words_V_data_V_1_ack_out <= dout_words_TREADY;
    dout_words_V_data_V_1_data_out <= ap_const_lv8_10;
    dout_words_V_data_V_1_sel <= dout_words_V_data_V_1_sel_rd;

    dout_words_V_data_V_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dout_words_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            dout_words_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    dout_words_V_data_V_1_vld_out <= dout_words_V_data_V_1_state(0);
    dout_words_V_tlast_1_ack_in <= dout_words_V_tlast_1_state(1);
    dout_words_V_tlast_1_ack_out <= dout_words_TREADY;
    dout_words_V_tlast_1_data_out <= ap_const_logic_1;
    dout_words_V_tlast_1_sel <= dout_words_V_tlast_1_sel_rd;

    dout_words_V_tlast_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dout_words_V_tlast_1_vld_in <= ap_const_logic_1;
        else 
            dout_words_V_tlast_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    dout_words_V_tlast_1_vld_out <= dout_words_V_tlast_1_state(0);
end behav;
