// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="first_counter,hls_ip_2018_3,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=148.646750,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=5310,HLS_VERSION=2018_3}" *)

module first_counter (
        clock,
        reset,
        enable,
        out_counter
);


input   clock;
input   reset;
input   enable;
output  [3:0] out_counter;

wire   [3:0] StgValue_10_first_counter_increment_fu_48_out_counter;
wire    StgValue_10_first_counter_increment_fu_48_out_counter_ap_vld;
wire   [3:0] StgValue_10_first_counter_increment_fu_48_first_counter_count_V_o;
wire    StgValue_10_first_counter_increment_fu_48_first_counter_count_V_o_ap_vld;
wire   [0:0] first_counter_ssd_load_fu_62_p1;

first_counter_increment StgValue_10_first_counter_increment_fu_48(
    .reset(reset),
    .enable(enable),
    .out_counter(StgValue_10_first_counter_increment_fu_48_out_counter),
    .out_counter_ap_vld(StgValue_10_first_counter_increment_fu_48_out_counter_ap_vld),
    .first_counter_count_V_i(StgValue_10_first_counter_increment_fu_48_first_counter_count_V_o),
    .first_counter_count_V_o(StgValue_10_first_counter_increment_fu_48_first_counter_count_V_o),
    .first_counter_count_V_o_ap_vld(StgValue_10_first_counter_increment_fu_48_first_counter_count_V_o_ap_vld)
);

assign first_counter_ssd_load_fu_62_p1 = 1'd0;

assign out_counter = StgValue_10_first_counter_increment_fu_48_out_counter;

endmodule //first_counter
