// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "first_counter_increment.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic first_counter_increment::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic first_counter_increment::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> first_counter_increment::ap_ST_fsm_state2 = "10";
const sc_lv<32> first_counter_increment::ap_const_lv32_1 = "1";
const sc_lv<1> first_counter_increment::ap_const_lv1_1 = "1";
const sc_lv<4> first_counter_increment::ap_const_lv4_1 = "1";
const bool first_counter_increment::ap_const_boolean_1 = true;

first_counter_increment::first_counter_increment(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_first_counter_count_V_o);
    sensitive << ( tmp_read_fu_68_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( v_V_fu_94_p2 );

    SC_METHOD(thread_first_counter_count_V_o_ap_vld);
    sensitive << ( tmp_read_fu_68_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_out_counter);
    sensitive << ( tmp_read_fu_68_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( v_V_fu_94_p2 );

    SC_METHOD(thread_out_counter_ap_vld);
    sensitive << ( tmp_read_fu_68_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_read_fu_68_p2);
    sensitive << ( enable );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_v_V_fu_94_p2);
    sensitive << ( first_counter_count_V_i );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );

    ap_CS_fsm = "10";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "first_counter_increment_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, enable, "(port)enable");
    sc_trace(mVcdFile, out_counter, "(port)out_counter");
    sc_trace(mVcdFile, out_counter_ap_vld, "(port)out_counter_ap_vld");
    sc_trace(mVcdFile, first_counter_count_V_i, "(port)first_counter_count_V_i");
    sc_trace(mVcdFile, first_counter_count_V_o, "(port)first_counter_count_V_o");
    sc_trace(mVcdFile, first_counter_count_V_o_ap_vld, "(port)first_counter_count_V_o_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, tmp_read_fu_68_p2, "tmp_read_fu_68_p2");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, v_V_fu_94_p2, "v_V_fu_94_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

first_counter_increment::~first_counter_increment() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void first_counter_increment::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state2;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
}

void first_counter_increment::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void first_counter_increment::thread_first_counter_count_V_o() {
    first_counter_count_V_o = v_V_fu_94_p2.read();
}

void first_counter_increment::thread_first_counter_count_V_o_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_read_fu_68_p2.read(), ap_const_lv1_1))) {
        first_counter_count_V_o_ap_vld = ap_const_logic_1;
    } else {
        first_counter_count_V_o_ap_vld = ap_const_logic_0;
    }
}

void first_counter_increment::thread_out_counter() {
    out_counter = v_V_fu_94_p2.read();
}

void first_counter_increment::thread_out_counter_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_read_fu_68_p2.read(), ap_const_lv1_1))) {
        out_counter_ap_vld = ap_const_logic_1;
    } else {
        out_counter_ap_vld = ap_const_logic_0;
    }
}

void first_counter_increment::thread_tmp_read_fu_68_p2() {
    tmp_read_fu_68_p2 =  (sc_lv<1>) (enable.read());
}

void first_counter_increment::thread_v_V_fu_94_p2() {
    v_V_fu_94_p2 = (!first_counter_count_V_i.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(first_counter_count_V_i.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void first_counter_increment::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

