-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity first_counter is
port (
    clock : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    enable : IN STD_LOGIC;
    out_counter : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of first_counter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "first_counter,hls_ip_2018_3,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=148.646750,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=5310,HLS_VERSION=2018_3}";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal StgValue_10_first_counter_increment_fu_48_out_counter : STD_LOGIC_VECTOR (3 downto 0);
    signal StgValue_10_first_counter_increment_fu_48_out_counter_ap_vld : STD_LOGIC;
    signal StgValue_10_first_counter_increment_fu_48_first_counter_count_V_o : STD_LOGIC_VECTOR (3 downto 0);
    signal StgValue_10_first_counter_increment_fu_48_first_counter_count_V_o_ap_vld : STD_LOGIC;
    signal first_counter_ssd_load_fu_62_p1 : STD_LOGIC_VECTOR (0 downto 0);

    component first_counter_increment IS
    port (
        reset : IN STD_LOGIC;
        enable : IN STD_LOGIC;
        out_counter : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_counter_ap_vld : OUT STD_LOGIC;
        first_counter_count_V_i : IN STD_LOGIC_VECTOR (3 downto 0);
        first_counter_count_V_o : OUT STD_LOGIC_VECTOR (3 downto 0);
        first_counter_count_V_o_ap_vld : OUT STD_LOGIC );
    end component;



begin
    StgValue_10_first_counter_increment_fu_48 : component first_counter_increment
    port map (
        reset => reset,
        enable => enable,
        out_counter => StgValue_10_first_counter_increment_fu_48_out_counter,
        out_counter_ap_vld => StgValue_10_first_counter_increment_fu_48_out_counter_ap_vld,
        first_counter_count_V_i => StgValue_10_first_counter_increment_fu_48_first_counter_count_V_o,
        first_counter_count_V_o => StgValue_10_first_counter_increment_fu_48_first_counter_count_V_o,
        first_counter_count_V_o_ap_vld => StgValue_10_first_counter_increment_fu_48_first_counter_count_V_o_ap_vld);




    first_counter_ssd_load_fu_62_p1 <= ap_const_lv1_0;
    out_counter <= StgValue_10_first_counter_increment_fu_48_out_counter;
end behav;
