// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _llr_HH_
#define _llr_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct llr : public sc_module {
    // Port declarations 25
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<128> > dt_TDATA;
    sc_in< sc_logic > dt_TVALID;
    sc_out< sc_logic > dt_TREADY;
    sc_in< sc_logic > dt_TLAST;
    sc_out< sc_lv<128> > din_TDATA;
    sc_out< sc_logic > din_TVALID;
    sc_in< sc_logic > din_TREADY;
    sc_out< sc_logic > din_TLAST;
    sc_out< sc_lv<32> > control_V_TDATA;
    sc_out< sc_logic > control_V_TVALID;
    sc_in< sc_logic > control_V_TREADY;
    sc_out< sc_lv<8> > din_words_TDATA;
    sc_out< sc_logic > din_words_TVALID;
    sc_in< sc_logic > din_words_TREADY;
    sc_out< sc_logic > din_words_TLAST;
    sc_out< sc_lv<8> > dout_words_TDATA;
    sc_out< sc_logic > dout_words_TVALID;
    sc_in< sc_logic > dout_words_TREADY;
    sc_out< sc_logic > dout_words_TLAST;


    // Module declarations
    llr(sc_module_name name);
    SC_HAS_PROCESS(llr);

    ~llr();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<128> > dt_V_data_V_0_data_out;
    sc_signal< sc_logic > dt_V_data_V_0_vld_in;
    sc_signal< sc_logic > dt_V_data_V_0_vld_out;
    sc_signal< sc_logic > dt_V_data_V_0_ack_in;
    sc_signal< sc_logic > dt_V_data_V_0_ack_out;
    sc_signal< sc_lv<128> > dt_V_data_V_0_payload_A;
    sc_signal< sc_lv<128> > dt_V_data_V_0_payload_B;
    sc_signal< sc_logic > dt_V_data_V_0_sel_rd;
    sc_signal< sc_logic > dt_V_data_V_0_sel_wr;
    sc_signal< sc_logic > dt_V_data_V_0_sel;
    sc_signal< sc_logic > dt_V_data_V_0_load_A;
    sc_signal< sc_logic > dt_V_data_V_0_load_B;
    sc_signal< sc_lv<2> > dt_V_data_V_0_state;
    sc_signal< sc_logic > dt_V_data_V_0_state_cmp_full;
    sc_signal< sc_logic > dt_V_tlast_0_vld_in;
    sc_signal< sc_logic > dt_V_tlast_0_ack_out;
    sc_signal< sc_lv<2> > dt_V_tlast_0_state;
    sc_signal< sc_lv<128> > din_V_data_V_1_data_out;
    sc_signal< sc_logic > din_V_data_V_1_vld_in;
    sc_signal< sc_logic > din_V_data_V_1_vld_out;
    sc_signal< sc_logic > din_V_data_V_1_ack_in;
    sc_signal< sc_logic > din_V_data_V_1_ack_out;
    sc_signal< sc_lv<128> > din_V_data_V_1_payload_A;
    sc_signal< sc_lv<128> > din_V_data_V_1_payload_B;
    sc_signal< sc_logic > din_V_data_V_1_sel_rd;
    sc_signal< sc_logic > din_V_data_V_1_sel_wr;
    sc_signal< sc_logic > din_V_data_V_1_sel;
    sc_signal< sc_logic > din_V_data_V_1_load_A;
    sc_signal< sc_logic > din_V_data_V_1_load_B;
    sc_signal< sc_lv<2> > din_V_data_V_1_state;
    sc_signal< sc_logic > din_V_data_V_1_state_cmp_full;
    sc_signal< sc_logic > din_V_tlast_1_data_out;
    sc_signal< sc_logic > din_V_tlast_1_vld_in;
    sc_signal< sc_logic > din_V_tlast_1_vld_out;
    sc_signal< sc_logic > din_V_tlast_1_ack_in;
    sc_signal< sc_logic > din_V_tlast_1_ack_out;
    sc_signal< sc_logic > din_V_tlast_1_payload_A;
    sc_signal< sc_logic > din_V_tlast_1_payload_B;
    sc_signal< sc_logic > din_V_tlast_1_sel_rd;
    sc_signal< sc_logic > din_V_tlast_1_sel_wr;
    sc_signal< sc_logic > din_V_tlast_1_sel;
    sc_signal< sc_logic > din_V_tlast_1_load_A;
    sc_signal< sc_logic > din_V_tlast_1_load_B;
    sc_signal< sc_lv<2> > din_V_tlast_1_state;
    sc_signal< sc_logic > din_V_tlast_1_state_cmp_full;
    sc_signal< sc_lv<32> > control_V_1_data_out;
    sc_signal< sc_logic > control_V_1_vld_in;
    sc_signal< sc_logic > control_V_1_vld_out;
    sc_signal< sc_logic > control_V_1_ack_in;
    sc_signal< sc_logic > control_V_1_ack_out;
    sc_signal< sc_logic > control_V_1_sel_rd;
    sc_signal< sc_logic > control_V_1_sel;
    sc_signal< sc_lv<2> > control_V_1_state;
    sc_signal< sc_lv<8> > din_words_V_data_V_1_data_out;
    sc_signal< sc_logic > din_words_V_data_V_1_vld_in;
    sc_signal< sc_logic > din_words_V_data_V_1_vld_out;
    sc_signal< sc_logic > din_words_V_data_V_1_ack_in;
    sc_signal< sc_logic > din_words_V_data_V_1_ack_out;
    sc_signal< sc_logic > din_words_V_data_V_1_sel_rd;
    sc_signal< sc_logic > din_words_V_data_V_1_sel;
    sc_signal< sc_lv<2> > din_words_V_data_V_1_state;
    sc_signal< sc_logic > din_words_V_tlast_1_data_out;
    sc_signal< sc_logic > din_words_V_tlast_1_vld_in;
    sc_signal< sc_logic > din_words_V_tlast_1_vld_out;
    sc_signal< sc_logic > din_words_V_tlast_1_ack_in;
    sc_signal< sc_logic > din_words_V_tlast_1_ack_out;
    sc_signal< sc_logic > din_words_V_tlast_1_sel_rd;
    sc_signal< sc_logic > din_words_V_tlast_1_sel;
    sc_signal< sc_lv<2> > din_words_V_tlast_1_state;
    sc_signal< sc_lv<8> > dout_words_V_data_V_1_data_out;
    sc_signal< sc_logic > dout_words_V_data_V_1_vld_in;
    sc_signal< sc_logic > dout_words_V_data_V_1_vld_out;
    sc_signal< sc_logic > dout_words_V_data_V_1_ack_in;
    sc_signal< sc_logic > dout_words_V_data_V_1_ack_out;
    sc_signal< sc_logic > dout_words_V_data_V_1_sel_rd;
    sc_signal< sc_logic > dout_words_V_data_V_1_sel;
    sc_signal< sc_lv<2> > dout_words_V_data_V_1_state;
    sc_signal< sc_logic > dout_words_V_tlast_1_data_out;
    sc_signal< sc_logic > dout_words_V_tlast_1_vld_in;
    sc_signal< sc_logic > dout_words_V_tlast_1_vld_out;
    sc_signal< sc_logic > dout_words_V_tlast_1_ack_in;
    sc_signal< sc_logic > dout_words_V_tlast_1_ack_out;
    sc_signal< sc_logic > dout_words_V_tlast_1_sel_rd;
    sc_signal< sc_logic > dout_words_V_tlast_1_sel;
    sc_signal< sc_lv<2> > dout_words_V_tlast_1_state;
    sc_signal< sc_logic > dt_TDATA_blk_n;
    sc_signal< sc_logic > din_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_5_fu_135_p2;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > control_V_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > din_words_TDATA_blk_n;
    sc_signal< sc_logic > dout_words_TDATA_blk_n;
    sc_signal< sc_lv<128> > tmp_data_V_reg_171;
    sc_signal< bool > ap_block_state1;
    sc_signal< bool > ap_block_state1_io;
    sc_signal< sc_lv<128> > temp_data_V_1_fu_151_p1;
    sc_signal< sc_lv<128> > temp_data_V_1_reg_179;
    sc_signal< bool > ap_block_state3;
    sc_signal< bool > ap_block_state3_io;
    sc_signal< sc_lv<1> > tmp_tlast_fu_155_p2;
    sc_signal< sc_lv<128> > tmp_data_V_4_cast_fu_162_p3;
    sc_signal< sc_lv<128> > lhs_V_reg_114;
    sc_signal< bool > ap_block_state2_io;
    sc_signal< sc_lv<64> > tmp_fu_127_p1;
    sc_signal< sc_lv<127> > tmp_2_fu_141_p4;
    sc_signal< sc_lv<1> > tmp_1_fu_131_p1;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_FC000004;
    static const sc_lv<8> ap_const_lv8_10;
    static const sc_lv<8> ap_const_lv8_5;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_7F;
    static const sc_lv<127> ap_const_lv127_0;
    static const sc_lv<128> ap_const_lv128_lc_1;
    static const sc_lv<128> ap_const_lv128_lc_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_block_state1();
    void thread_ap_block_state1_io();
    void thread_ap_block_state2_io();
    void thread_ap_block_state3();
    void thread_ap_block_state3_io();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_control_V_1_ack_in();
    void thread_control_V_1_ack_out();
    void thread_control_V_1_data_out();
    void thread_control_V_1_sel();
    void thread_control_V_1_vld_in();
    void thread_control_V_1_vld_out();
    void thread_control_V_TDATA();
    void thread_control_V_TDATA_blk_n();
    void thread_control_V_TVALID();
    void thread_din_TDATA();
    void thread_din_TDATA_blk_n();
    void thread_din_TLAST();
    void thread_din_TVALID();
    void thread_din_V_data_V_1_ack_in();
    void thread_din_V_data_V_1_ack_out();
    void thread_din_V_data_V_1_data_out();
    void thread_din_V_data_V_1_load_A();
    void thread_din_V_data_V_1_load_B();
    void thread_din_V_data_V_1_sel();
    void thread_din_V_data_V_1_state_cmp_full();
    void thread_din_V_data_V_1_vld_in();
    void thread_din_V_data_V_1_vld_out();
    void thread_din_V_tlast_1_ack_in();
    void thread_din_V_tlast_1_ack_out();
    void thread_din_V_tlast_1_data_out();
    void thread_din_V_tlast_1_load_A();
    void thread_din_V_tlast_1_load_B();
    void thread_din_V_tlast_1_sel();
    void thread_din_V_tlast_1_state_cmp_full();
    void thread_din_V_tlast_1_vld_in();
    void thread_din_V_tlast_1_vld_out();
    void thread_din_words_TDATA();
    void thread_din_words_TDATA_blk_n();
    void thread_din_words_TLAST();
    void thread_din_words_TVALID();
    void thread_din_words_V_data_V_1_ack_in();
    void thread_din_words_V_data_V_1_ack_out();
    void thread_din_words_V_data_V_1_data_out();
    void thread_din_words_V_data_V_1_sel();
    void thread_din_words_V_data_V_1_vld_in();
    void thread_din_words_V_data_V_1_vld_out();
    void thread_din_words_V_tlast_1_ack_in();
    void thread_din_words_V_tlast_1_ack_out();
    void thread_din_words_V_tlast_1_data_out();
    void thread_din_words_V_tlast_1_sel();
    void thread_din_words_V_tlast_1_vld_in();
    void thread_din_words_V_tlast_1_vld_out();
    void thread_dout_words_TDATA();
    void thread_dout_words_TDATA_blk_n();
    void thread_dout_words_TLAST();
    void thread_dout_words_TVALID();
    void thread_dout_words_V_data_V_1_ack_in();
    void thread_dout_words_V_data_V_1_ack_out();
    void thread_dout_words_V_data_V_1_data_out();
    void thread_dout_words_V_data_V_1_sel();
    void thread_dout_words_V_data_V_1_vld_in();
    void thread_dout_words_V_data_V_1_vld_out();
    void thread_dout_words_V_tlast_1_ack_in();
    void thread_dout_words_V_tlast_1_ack_out();
    void thread_dout_words_V_tlast_1_data_out();
    void thread_dout_words_V_tlast_1_sel();
    void thread_dout_words_V_tlast_1_vld_in();
    void thread_dout_words_V_tlast_1_vld_out();
    void thread_dt_TDATA_blk_n();
    void thread_dt_TREADY();
    void thread_dt_V_data_V_0_ack_in();
    void thread_dt_V_data_V_0_ack_out();
    void thread_dt_V_data_V_0_data_out();
    void thread_dt_V_data_V_0_load_A();
    void thread_dt_V_data_V_0_load_B();
    void thread_dt_V_data_V_0_sel();
    void thread_dt_V_data_V_0_state_cmp_full();
    void thread_dt_V_data_V_0_vld_in();
    void thread_dt_V_data_V_0_vld_out();
    void thread_dt_V_tlast_0_ack_out();
    void thread_dt_V_tlast_0_vld_in();
    void thread_temp_data_V_1_fu_151_p1();
    void thread_tmp_1_fu_131_p1();
    void thread_tmp_2_fu_141_p4();
    void thread_tmp_5_fu_135_p2();
    void thread_tmp_data_V_4_cast_fu_162_p3();
    void thread_tmp_fu_127_p1();
    void thread_tmp_tlast_fu_155_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
