// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "datag.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic datag::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic datag::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> datag::ap_ST_fsm_state1 = "1";
const sc_lv<2> datag::ap_ST_fsm_state2 = "10";
const sc_lv<32> datag::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool datag::ap_const_boolean_1 = true;
const sc_lv<1> datag::ap_const_lv1_0 = "0";
const sc_lv<1> datag::ap_const_lv1_1 = "1";
const sc_lv<2> datag::ap_const_lv2_0 = "00";
const sc_lv<2> datag::ap_const_lv2_2 = "10";
const sc_lv<2> datag::ap_const_lv2_3 = "11";
const sc_lv<2> datag::ap_const_lv2_1 = "1";
const sc_lv<32> datag::ap_const_lv32_1 = "1";
const sc_lv<32> datag::ap_const_lv32_48F55FC = "100100011110101010111111100";
const sc_lv<8> datag::ap_const_lv8_10 = "10000";
const sc_lv<128> datag::ap_const_lv128_lc_1 = "1001010111101110100000011001101001110110";

datag::datag(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1_io);
    sensitive << ( din_V_data_V_1_ack_in );
    sensitive << ( control_V_1_ack_in );
    sensitive << ( din_words_V_data_V_1_ack_in );
    sensitive << ( dout_words_V_data_V_1_ack_in );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( din_V_data_V_1_ack_in );
    sensitive << ( din_V_tlast_1_ack_in );
    sensitive << ( control_V_1_ack_in );
    sensitive << ( din_words_V_data_V_1_ack_in );
    sensitive << ( din_words_V_tlast_1_ack_in );
    sensitive << ( dout_words_V_data_V_1_ack_in );
    sensitive << ( dout_words_V_tlast_1_ack_in );

    SC_METHOD(thread_ap_block_state2_io);
    sensitive << ( din_V_data_V_1_ack_in );
    sensitive << ( control_V_1_ack_in );
    sensitive << ( din_words_V_data_V_1_ack_in );
    sensitive << ( dout_words_V_data_V_1_ack_in );

    SC_METHOD(thread_ap_done);
    sensitive << ( din_V_data_V_1_ack_in );
    sensitive << ( din_V_data_V_1_state );
    sensitive << ( din_V_tlast_1_ack_in );
    sensitive << ( din_V_tlast_1_state );
    sensitive << ( control_V_1_ack_in );
    sensitive << ( control_V_1_state );
    sensitive << ( din_words_V_data_V_1_ack_in );
    sensitive << ( din_words_V_data_V_1_state );
    sensitive << ( din_words_V_tlast_1_ack_in );
    sensitive << ( din_words_V_tlast_1_state );
    sensitive << ( dout_words_V_data_V_1_ack_in );
    sensitive << ( dout_words_V_data_V_1_state );
    sensitive << ( dout_words_V_tlast_1_ack_in );
    sensitive << ( dout_words_V_tlast_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( din_V_data_V_1_ack_in );
    sensitive << ( din_V_data_V_1_state );
    sensitive << ( din_V_tlast_1_ack_in );
    sensitive << ( din_V_tlast_1_state );
    sensitive << ( control_V_1_ack_in );
    sensitive << ( control_V_1_state );
    sensitive << ( din_words_V_data_V_1_ack_in );
    sensitive << ( din_words_V_data_V_1_state );
    sensitive << ( din_words_V_tlast_1_ack_in );
    sensitive << ( din_words_V_tlast_1_state );
    sensitive << ( dout_words_V_data_V_1_ack_in );
    sensitive << ( dout_words_V_data_V_1_state );
    sensitive << ( dout_words_V_tlast_1_ack_in );
    sensitive << ( dout_words_V_tlast_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_control_V_1_ack_in);
    sensitive << ( control_V_1_state );

    SC_METHOD(thread_control_V_1_ack_out);
    sensitive << ( control_V_TREADY );

    SC_METHOD(thread_control_V_1_data_out);
    sensitive << ( control_V_1_sel );

    SC_METHOD(thread_control_V_1_sel);
    sensitive << ( control_V_1_sel_rd );

    SC_METHOD(thread_control_V_1_vld_in);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_control_V_1_vld_out);
    sensitive << ( control_V_1_state );

    SC_METHOD(thread_control_V_TDATA);
    sensitive << ( control_V_1_data_out );

    SC_METHOD(thread_control_V_TDATA_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( control_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_control_V_TVALID);
    sensitive << ( control_V_1_state );

    SC_METHOD(thread_din_TDATA);
    sensitive << ( din_V_data_V_1_data_out );

    SC_METHOD(thread_din_TDATA_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( din_V_data_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_din_TLAST);
    sensitive << ( din_V_tlast_1_data_out );

    SC_METHOD(thread_din_TVALID);
    sensitive << ( din_V_tlast_1_state );

    SC_METHOD(thread_din_V_data_V_1_ack_in);
    sensitive << ( din_V_data_V_1_state );

    SC_METHOD(thread_din_V_data_V_1_ack_out);
    sensitive << ( din_TREADY );

    SC_METHOD(thread_din_V_data_V_1_data_out);
    sensitive << ( din_V_data_V_1_sel );

    SC_METHOD(thread_din_V_data_V_1_sel);
    sensitive << ( din_V_data_V_1_sel_rd );

    SC_METHOD(thread_din_V_data_V_1_vld_in);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_din_V_data_V_1_vld_out);
    sensitive << ( din_V_data_V_1_state );

    SC_METHOD(thread_din_V_tlast_1_ack_in);
    sensitive << ( din_V_tlast_1_state );

    SC_METHOD(thread_din_V_tlast_1_ack_out);
    sensitive << ( din_TREADY );

    SC_METHOD(thread_din_V_tlast_1_data_out);
    sensitive << ( din_V_tlast_1_sel );

    SC_METHOD(thread_din_V_tlast_1_sel);
    sensitive << ( din_V_tlast_1_sel_rd );

    SC_METHOD(thread_din_V_tlast_1_vld_in);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_din_V_tlast_1_vld_out);
    sensitive << ( din_V_tlast_1_state );

    SC_METHOD(thread_din_words_TDATA);
    sensitive << ( din_words_V_data_V_1_data_out );

    SC_METHOD(thread_din_words_TDATA_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( din_words_V_data_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_din_words_TLAST);
    sensitive << ( din_words_V_tlast_1_data_out );

    SC_METHOD(thread_din_words_TVALID);
    sensitive << ( din_words_V_tlast_1_state );

    SC_METHOD(thread_din_words_V_data_V_1_ack_in);
    sensitive << ( din_words_V_data_V_1_state );

    SC_METHOD(thread_din_words_V_data_V_1_ack_out);
    sensitive << ( din_words_TREADY );

    SC_METHOD(thread_din_words_V_data_V_1_data_out);
    sensitive << ( din_words_V_data_V_1_sel );

    SC_METHOD(thread_din_words_V_data_V_1_sel);
    sensitive << ( din_words_V_data_V_1_sel_rd );

    SC_METHOD(thread_din_words_V_data_V_1_vld_in);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_din_words_V_data_V_1_vld_out);
    sensitive << ( din_words_V_data_V_1_state );

    SC_METHOD(thread_din_words_V_tlast_1_ack_in);
    sensitive << ( din_words_V_tlast_1_state );

    SC_METHOD(thread_din_words_V_tlast_1_ack_out);
    sensitive << ( din_words_TREADY );

    SC_METHOD(thread_din_words_V_tlast_1_data_out);
    sensitive << ( din_words_V_tlast_1_sel );

    SC_METHOD(thread_din_words_V_tlast_1_sel);
    sensitive << ( din_words_V_tlast_1_sel_rd );

    SC_METHOD(thread_din_words_V_tlast_1_vld_in);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_din_words_V_tlast_1_vld_out);
    sensitive << ( din_words_V_tlast_1_state );

    SC_METHOD(thread_dout_words_TDATA);
    sensitive << ( dout_words_V_data_V_1_data_out );

    SC_METHOD(thread_dout_words_TDATA_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( dout_words_V_data_V_1_state );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_dout_words_TLAST);
    sensitive << ( dout_words_V_tlast_1_data_out );

    SC_METHOD(thread_dout_words_TVALID);
    sensitive << ( dout_words_V_tlast_1_state );

    SC_METHOD(thread_dout_words_V_data_V_1_ack_in);
    sensitive << ( dout_words_V_data_V_1_state );

    SC_METHOD(thread_dout_words_V_data_V_1_ack_out);
    sensitive << ( dout_words_TREADY );

    SC_METHOD(thread_dout_words_V_data_V_1_data_out);
    sensitive << ( dout_words_V_data_V_1_sel );

    SC_METHOD(thread_dout_words_V_data_V_1_sel);
    sensitive << ( dout_words_V_data_V_1_sel_rd );

    SC_METHOD(thread_dout_words_V_data_V_1_vld_in);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_dout_words_V_data_V_1_vld_out);
    sensitive << ( dout_words_V_data_V_1_state );

    SC_METHOD(thread_dout_words_V_tlast_1_ack_in);
    sensitive << ( dout_words_V_tlast_1_state );

    SC_METHOD(thread_dout_words_V_tlast_1_ack_out);
    sensitive << ( dout_words_TREADY );

    SC_METHOD(thread_dout_words_V_tlast_1_data_out);
    sensitive << ( dout_words_V_tlast_1_sel );

    SC_METHOD(thread_dout_words_V_tlast_1_sel);
    sensitive << ( dout_words_V_tlast_1_sel_rd );

    SC_METHOD(thread_dout_words_V_tlast_1_vld_in);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_dout_words_V_tlast_1_vld_out);
    sensitive << ( dout_words_V_tlast_1_state );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( din_V_data_V_1_ack_in );
    sensitive << ( din_V_data_V_1_state );
    sensitive << ( din_V_tlast_1_ack_in );
    sensitive << ( din_V_tlast_1_state );
    sensitive << ( control_V_1_ack_in );
    sensitive << ( control_V_1_state );
    sensitive << ( din_words_V_data_V_1_ack_in );
    sensitive << ( din_words_V_data_V_1_state );
    sensitive << ( din_words_V_tlast_1_ack_in );
    sensitive << ( din_words_V_tlast_1_state );
    sensitive << ( dout_words_V_data_V_1_ack_in );
    sensitive << ( dout_words_V_data_V_1_state );
    sensitive << ( dout_words_V_tlast_1_ack_in );
    sensitive << ( dout_words_V_tlast_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_state1_io );
    sensitive << ( ap_block_state2_io );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "01";
    din_V_data_V_1_sel_rd = SC_LOGIC_0;
    din_V_data_V_1_state = "00";
    din_V_tlast_1_sel_rd = SC_LOGIC_0;
    din_V_tlast_1_state = "00";
    control_V_1_sel_rd = SC_LOGIC_0;
    control_V_1_state = "00";
    din_words_V_data_V_1_sel_rd = SC_LOGIC_0;
    din_words_V_data_V_1_state = "00";
    din_words_V_tlast_1_sel_rd = SC_LOGIC_0;
    din_words_V_tlast_1_state = "00";
    dout_words_V_data_V_1_sel_rd = SC_LOGIC_0;
    dout_words_V_data_V_1_state = "00";
    dout_words_V_tlast_1_sel_rd = SC_LOGIC_0;
    dout_words_V_tlast_1_state = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "datag_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, din_TDATA, "(port)din_TDATA");
    sc_trace(mVcdFile, din_TVALID, "(port)din_TVALID");
    sc_trace(mVcdFile, din_TREADY, "(port)din_TREADY");
    sc_trace(mVcdFile, din_TLAST, "(port)din_TLAST");
    sc_trace(mVcdFile, control_V_TDATA, "(port)control_V_TDATA");
    sc_trace(mVcdFile, control_V_TVALID, "(port)control_V_TVALID");
    sc_trace(mVcdFile, control_V_TREADY, "(port)control_V_TREADY");
    sc_trace(mVcdFile, din_words_TDATA, "(port)din_words_TDATA");
    sc_trace(mVcdFile, din_words_TVALID, "(port)din_words_TVALID");
    sc_trace(mVcdFile, din_words_TREADY, "(port)din_words_TREADY");
    sc_trace(mVcdFile, din_words_TLAST, "(port)din_words_TLAST");
    sc_trace(mVcdFile, dout_words_TDATA, "(port)dout_words_TDATA");
    sc_trace(mVcdFile, dout_words_TVALID, "(port)dout_words_TVALID");
    sc_trace(mVcdFile, dout_words_TREADY, "(port)dout_words_TREADY");
    sc_trace(mVcdFile, dout_words_TLAST, "(port)dout_words_TLAST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, din_V_data_V_1_data_out, "din_V_data_V_1_data_out");
    sc_trace(mVcdFile, din_V_data_V_1_vld_in, "din_V_data_V_1_vld_in");
    sc_trace(mVcdFile, din_V_data_V_1_vld_out, "din_V_data_V_1_vld_out");
    sc_trace(mVcdFile, din_V_data_V_1_ack_in, "din_V_data_V_1_ack_in");
    sc_trace(mVcdFile, din_V_data_V_1_ack_out, "din_V_data_V_1_ack_out");
    sc_trace(mVcdFile, din_V_data_V_1_sel_rd, "din_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, din_V_data_V_1_sel, "din_V_data_V_1_sel");
    sc_trace(mVcdFile, din_V_data_V_1_state, "din_V_data_V_1_state");
    sc_trace(mVcdFile, din_V_tlast_1_data_out, "din_V_tlast_1_data_out");
    sc_trace(mVcdFile, din_V_tlast_1_vld_in, "din_V_tlast_1_vld_in");
    sc_trace(mVcdFile, din_V_tlast_1_vld_out, "din_V_tlast_1_vld_out");
    sc_trace(mVcdFile, din_V_tlast_1_ack_in, "din_V_tlast_1_ack_in");
    sc_trace(mVcdFile, din_V_tlast_1_ack_out, "din_V_tlast_1_ack_out");
    sc_trace(mVcdFile, din_V_tlast_1_sel_rd, "din_V_tlast_1_sel_rd");
    sc_trace(mVcdFile, din_V_tlast_1_sel, "din_V_tlast_1_sel");
    sc_trace(mVcdFile, din_V_tlast_1_state, "din_V_tlast_1_state");
    sc_trace(mVcdFile, control_V_1_data_out, "control_V_1_data_out");
    sc_trace(mVcdFile, control_V_1_vld_in, "control_V_1_vld_in");
    sc_trace(mVcdFile, control_V_1_vld_out, "control_V_1_vld_out");
    sc_trace(mVcdFile, control_V_1_ack_in, "control_V_1_ack_in");
    sc_trace(mVcdFile, control_V_1_ack_out, "control_V_1_ack_out");
    sc_trace(mVcdFile, control_V_1_sel_rd, "control_V_1_sel_rd");
    sc_trace(mVcdFile, control_V_1_sel, "control_V_1_sel");
    sc_trace(mVcdFile, control_V_1_state, "control_V_1_state");
    sc_trace(mVcdFile, din_words_V_data_V_1_data_out, "din_words_V_data_V_1_data_out");
    sc_trace(mVcdFile, din_words_V_data_V_1_vld_in, "din_words_V_data_V_1_vld_in");
    sc_trace(mVcdFile, din_words_V_data_V_1_vld_out, "din_words_V_data_V_1_vld_out");
    sc_trace(mVcdFile, din_words_V_data_V_1_ack_in, "din_words_V_data_V_1_ack_in");
    sc_trace(mVcdFile, din_words_V_data_V_1_ack_out, "din_words_V_data_V_1_ack_out");
    sc_trace(mVcdFile, din_words_V_data_V_1_sel_rd, "din_words_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, din_words_V_data_V_1_sel, "din_words_V_data_V_1_sel");
    sc_trace(mVcdFile, din_words_V_data_V_1_state, "din_words_V_data_V_1_state");
    sc_trace(mVcdFile, din_words_V_tlast_1_data_out, "din_words_V_tlast_1_data_out");
    sc_trace(mVcdFile, din_words_V_tlast_1_vld_in, "din_words_V_tlast_1_vld_in");
    sc_trace(mVcdFile, din_words_V_tlast_1_vld_out, "din_words_V_tlast_1_vld_out");
    sc_trace(mVcdFile, din_words_V_tlast_1_ack_in, "din_words_V_tlast_1_ack_in");
    sc_trace(mVcdFile, din_words_V_tlast_1_ack_out, "din_words_V_tlast_1_ack_out");
    sc_trace(mVcdFile, din_words_V_tlast_1_sel_rd, "din_words_V_tlast_1_sel_rd");
    sc_trace(mVcdFile, din_words_V_tlast_1_sel, "din_words_V_tlast_1_sel");
    sc_trace(mVcdFile, din_words_V_tlast_1_state, "din_words_V_tlast_1_state");
    sc_trace(mVcdFile, dout_words_V_data_V_1_data_out, "dout_words_V_data_V_1_data_out");
    sc_trace(mVcdFile, dout_words_V_data_V_1_vld_in, "dout_words_V_data_V_1_vld_in");
    sc_trace(mVcdFile, dout_words_V_data_V_1_vld_out, "dout_words_V_data_V_1_vld_out");
    sc_trace(mVcdFile, dout_words_V_data_V_1_ack_in, "dout_words_V_data_V_1_ack_in");
    sc_trace(mVcdFile, dout_words_V_data_V_1_ack_out, "dout_words_V_data_V_1_ack_out");
    sc_trace(mVcdFile, dout_words_V_data_V_1_sel_rd, "dout_words_V_data_V_1_sel_rd");
    sc_trace(mVcdFile, dout_words_V_data_V_1_sel, "dout_words_V_data_V_1_sel");
    sc_trace(mVcdFile, dout_words_V_data_V_1_state, "dout_words_V_data_V_1_state");
    sc_trace(mVcdFile, dout_words_V_tlast_1_data_out, "dout_words_V_tlast_1_data_out");
    sc_trace(mVcdFile, dout_words_V_tlast_1_vld_in, "dout_words_V_tlast_1_vld_in");
    sc_trace(mVcdFile, dout_words_V_tlast_1_vld_out, "dout_words_V_tlast_1_vld_out");
    sc_trace(mVcdFile, dout_words_V_tlast_1_ack_in, "dout_words_V_tlast_1_ack_in");
    sc_trace(mVcdFile, dout_words_V_tlast_1_ack_out, "dout_words_V_tlast_1_ack_out");
    sc_trace(mVcdFile, dout_words_V_tlast_1_sel_rd, "dout_words_V_tlast_1_sel_rd");
    sc_trace(mVcdFile, dout_words_V_tlast_1_sel, "dout_words_V_tlast_1_sel");
    sc_trace(mVcdFile, dout_words_V_tlast_1_state, "dout_words_V_tlast_1_state");
    sc_trace(mVcdFile, din_TDATA_blk_n, "din_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, control_V_TDATA_blk_n, "control_V_TDATA_blk_n");
    sc_trace(mVcdFile, din_words_TDATA_blk_n, "din_words_TDATA_blk_n");
    sc_trace(mVcdFile, dout_words_TDATA_blk_n, "dout_words_TDATA_blk_n");
    sc_trace(mVcdFile, ap_block_state1_io, "ap_block_state1_io");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, ap_block_state2_io, "ap_block_state2_io");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("datag.hdltvin.dat");
    mHdltvoutHandle.open("datag.hdltvout.dat");
}

datag::~datag() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void datag::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        control_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, control_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, control_V_1_vld_out.read()))) {
            control_V_1_sel_rd =  (sc_logic) (~control_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        control_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, control_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, control_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, control_V_1_state.read())))) {
            control_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, control_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, control_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, control_V_1_state.read())))) {
            control_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, control_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, control_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, control_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, control_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, control_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, control_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, control_V_1_ack_out.read()))))) {
            control_V_1_state = ap_const_lv2_3;
        } else {
            control_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        din_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, din_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, din_V_data_V_1_vld_out.read()))) {
            din_V_data_V_1_sel_rd =  (sc_logic) (~din_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        din_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, din_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(din_V_data_V_1_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(din_V_data_V_1_state.read(), ap_const_lv2_2)))) {
            din_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, din_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(din_V_data_V_1_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(din_V_data_V_1_state.read(), ap_const_lv2_1)))) {
            din_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, din_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(din_V_data_V_1_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, din_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(din_V_data_V_1_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(din_V_data_V_1_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, din_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, din_V_data_V_1_ack_out.read()))))) {
            din_V_data_V_1_state = ap_const_lv2_3;
        } else {
            din_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        din_V_tlast_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, din_V_tlast_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, din_V_tlast_1_vld_out.read()))) {
            din_V_tlast_1_sel_rd =  (sc_logic) (~din_V_tlast_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        din_V_tlast_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, din_V_tlast_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, din_V_tlast_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, din_V_tlast_1_state.read())))) {
            din_V_tlast_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, din_V_tlast_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, din_V_tlast_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, din_V_tlast_1_state.read())))) {
            din_V_tlast_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, din_V_tlast_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, din_V_tlast_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, din_V_tlast_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, din_V_tlast_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, din_V_tlast_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, din_V_tlast_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, din_V_tlast_1_ack_out.read()))))) {
            din_V_tlast_1_state = ap_const_lv2_3;
        } else {
            din_V_tlast_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        din_words_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_data_V_1_vld_out.read()))) {
            din_words_V_data_V_1_sel_rd =  (sc_logic) (~din_words_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        din_words_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, din_words_V_data_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, din_words_V_data_V_1_state.read())))) {
            din_words_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, din_words_V_data_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, din_words_V_data_V_1_state.read())))) {
            din_words_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, din_words_V_data_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, din_words_V_data_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, din_words_V_data_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_data_V_1_ack_out.read()))))) {
            din_words_V_data_V_1_state = ap_const_lv2_3;
        } else {
            din_words_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        din_words_V_tlast_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_tlast_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_tlast_1_vld_out.read()))) {
            din_words_V_tlast_1_sel_rd =  (sc_logic) (~din_words_V_tlast_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        din_words_V_tlast_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_tlast_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, din_words_V_tlast_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, din_words_V_tlast_1_state.read())))) {
            din_words_V_tlast_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_tlast_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, din_words_V_tlast_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, din_words_V_tlast_1_state.read())))) {
            din_words_V_tlast_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_tlast_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, din_words_V_tlast_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_tlast_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, din_words_V_tlast_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, din_words_V_tlast_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_tlast_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, din_words_V_tlast_1_ack_out.read()))))) {
            din_words_V_tlast_1_state = ap_const_lv2_3;
        } else {
            din_words_V_tlast_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        dout_words_V_data_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_data_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_data_V_1_vld_out.read()))) {
            dout_words_V_data_V_1_sel_rd =  (sc_logic) (~dout_words_V_data_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        dout_words_V_data_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_data_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, dout_words_V_data_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, dout_words_V_data_V_1_state.read())))) {
            dout_words_V_data_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, dout_words_V_data_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, dout_words_V_data_V_1_state.read())))) {
            dout_words_V_data_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_data_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, dout_words_V_data_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_data_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, dout_words_V_data_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, dout_words_V_data_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_data_V_1_ack_out.read()))))) {
            dout_words_V_data_V_1_state = ap_const_lv2_3;
        } else {
            dout_words_V_data_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        dout_words_V_tlast_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_tlast_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_tlast_1_vld_out.read()))) {
            dout_words_V_tlast_1_sel_rd =  (sc_logic) (~dout_words_V_tlast_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        dout_words_V_tlast_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_tlast_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, dout_words_V_tlast_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, dout_words_V_tlast_1_state.read())))) {
            dout_words_V_tlast_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_tlast_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, dout_words_V_tlast_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, dout_words_V_tlast_1_state.read())))) {
            dout_words_V_tlast_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_tlast_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, dout_words_V_tlast_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_tlast_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, dout_words_V_tlast_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, dout_words_V_tlast_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_tlast_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, dout_words_V_tlast_1_ack_out.read()))))) {
            dout_words_V_tlast_1_state = ap_const_lv2_3;
        } else {
            dout_words_V_tlast_1_state = ap_const_lv2_2;
        }
    }
}

void datag::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void datag::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void datag::thread_ap_block_state1_io() {
    ap_block_state1_io = (esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_ack_in.read()));
}

void datag::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_ack_in.read()));
}

void datag::thread_ap_block_state2_io() {
    ap_block_state2_io = (esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_ack_in.read()));
}

void datag::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_state.read()[0]) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void datag::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void datag::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_state.read()[0]) && 
         esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_state.read()[0]) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void datag::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void datag::thread_control_V_1_ack_in() {
    control_V_1_ack_in = control_V_1_state.read()[1];
}

void datag::thread_control_V_1_ack_out() {
    control_V_1_ack_out = control_V_TREADY.read();
}

void datag::thread_control_V_1_data_out() {
    control_V_1_data_out = ap_const_lv32_48F55FC;
}

void datag::thread_control_V_1_sel() {
    control_V_1_sel = control_V_1_sel_rd.read();
}

void datag::thread_control_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        control_V_1_vld_in = ap_const_logic_1;
    } else {
        control_V_1_vld_in = ap_const_logic_0;
    }
}

void datag::thread_control_V_1_vld_out() {
    control_V_1_vld_out = control_V_1_state.read()[0];
}

void datag::thread_control_V_TDATA() {
    control_V_TDATA = control_V_1_data_out.read();
}

void datag::thread_control_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        control_V_TDATA_blk_n = control_V_1_state.read()[1];
    } else {
        control_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void datag::thread_control_V_TVALID() {
    control_V_TVALID = control_V_1_state.read()[0];
}

void datag::thread_din_TDATA() {
    din_TDATA = din_V_data_V_1_data_out.read();
}

void datag::thread_din_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        din_TDATA_blk_n = din_V_data_V_1_state.read()[1];
    } else {
        din_TDATA_blk_n = ap_const_logic_1;
    }
}

void datag::thread_din_TLAST() {
    din_TLAST = din_V_tlast_1_data_out.read();
}

void datag::thread_din_TVALID() {
    din_TVALID = din_V_tlast_1_state.read()[0];
}

void datag::thread_din_V_data_V_1_ack_in() {
    din_V_data_V_1_ack_in = din_V_data_V_1_state.read()[1];
}

void datag::thread_din_V_data_V_1_ack_out() {
    din_V_data_V_1_ack_out = din_TREADY.read();
}

void datag::thread_din_V_data_V_1_data_out() {
    din_V_data_V_1_data_out = ap_const_lv128_lc_1;
}

void datag::thread_din_V_data_V_1_sel() {
    din_V_data_V_1_sel = din_V_data_V_1_sel_rd.read();
}

void datag::thread_din_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        din_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        din_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void datag::thread_din_V_data_V_1_vld_out() {
    din_V_data_V_1_vld_out = din_V_data_V_1_state.read()[0];
}

void datag::thread_din_V_tlast_1_ack_in() {
    din_V_tlast_1_ack_in = din_V_tlast_1_state.read()[1];
}

void datag::thread_din_V_tlast_1_ack_out() {
    din_V_tlast_1_ack_out = din_TREADY.read();
}

void datag::thread_din_V_tlast_1_data_out() {
    din_V_tlast_1_data_out =  (sc_logic) (ap_const_lv1_1[0]);
}

void datag::thread_din_V_tlast_1_sel() {
    din_V_tlast_1_sel = din_V_tlast_1_sel_rd.read();
}

void datag::thread_din_V_tlast_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        din_V_tlast_1_vld_in = ap_const_logic_1;
    } else {
        din_V_tlast_1_vld_in = ap_const_logic_0;
    }
}

void datag::thread_din_V_tlast_1_vld_out() {
    din_V_tlast_1_vld_out = din_V_tlast_1_state.read()[0];
}

void datag::thread_din_words_TDATA() {
    din_words_TDATA = din_words_V_data_V_1_data_out.read();
}

void datag::thread_din_words_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        din_words_TDATA_blk_n = din_words_V_data_V_1_state.read()[1];
    } else {
        din_words_TDATA_blk_n = ap_const_logic_1;
    }
}

void datag::thread_din_words_TLAST() {
    din_words_TLAST = din_words_V_tlast_1_data_out.read();
}

void datag::thread_din_words_TVALID() {
    din_words_TVALID = din_words_V_tlast_1_state.read()[0];
}

void datag::thread_din_words_V_data_V_1_ack_in() {
    din_words_V_data_V_1_ack_in = din_words_V_data_V_1_state.read()[1];
}

void datag::thread_din_words_V_data_V_1_ack_out() {
    din_words_V_data_V_1_ack_out = din_words_TREADY.read();
}

void datag::thread_din_words_V_data_V_1_data_out() {
    din_words_V_data_V_1_data_out = ap_const_lv8_10;
}

void datag::thread_din_words_V_data_V_1_sel() {
    din_words_V_data_V_1_sel = din_words_V_data_V_1_sel_rd.read();
}

void datag::thread_din_words_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        din_words_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        din_words_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void datag::thread_din_words_V_data_V_1_vld_out() {
    din_words_V_data_V_1_vld_out = din_words_V_data_V_1_state.read()[0];
}

void datag::thread_din_words_V_tlast_1_ack_in() {
    din_words_V_tlast_1_ack_in = din_words_V_tlast_1_state.read()[1];
}

void datag::thread_din_words_V_tlast_1_ack_out() {
    din_words_V_tlast_1_ack_out = din_words_TREADY.read();
}

void datag::thread_din_words_V_tlast_1_data_out() {
    din_words_V_tlast_1_data_out =  (sc_logic) (ap_const_lv1_1[0]);
}

void datag::thread_din_words_V_tlast_1_sel() {
    din_words_V_tlast_1_sel = din_words_V_tlast_1_sel_rd.read();
}

void datag::thread_din_words_V_tlast_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        din_words_V_tlast_1_vld_in = ap_const_logic_1;
    } else {
        din_words_V_tlast_1_vld_in = ap_const_logic_0;
    }
}

void datag::thread_din_words_V_tlast_1_vld_out() {
    din_words_V_tlast_1_vld_out = din_words_V_tlast_1_state.read()[0];
}

void datag::thread_dout_words_TDATA() {
    dout_words_TDATA = dout_words_V_data_V_1_data_out.read();
}

void datag::thread_dout_words_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        dout_words_TDATA_blk_n = dout_words_V_data_V_1_state.read()[1];
    } else {
        dout_words_TDATA_blk_n = ap_const_logic_1;
    }
}

void datag::thread_dout_words_TLAST() {
    dout_words_TLAST = dout_words_V_tlast_1_data_out.read();
}

void datag::thread_dout_words_TVALID() {
    dout_words_TVALID = dout_words_V_tlast_1_state.read()[0];
}

void datag::thread_dout_words_V_data_V_1_ack_in() {
    dout_words_V_data_V_1_ack_in = dout_words_V_data_V_1_state.read()[1];
}

void datag::thread_dout_words_V_data_V_1_ack_out() {
    dout_words_V_data_V_1_ack_out = dout_words_TREADY.read();
}

void datag::thread_dout_words_V_data_V_1_data_out() {
    dout_words_V_data_V_1_data_out = ap_const_lv8_10;
}

void datag::thread_dout_words_V_data_V_1_sel() {
    dout_words_V_data_V_1_sel = dout_words_V_data_V_1_sel_rd.read();
}

void datag::thread_dout_words_V_data_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        dout_words_V_data_V_1_vld_in = ap_const_logic_1;
    } else {
        dout_words_V_data_V_1_vld_in = ap_const_logic_0;
    }
}

void datag::thread_dout_words_V_data_V_1_vld_out() {
    dout_words_V_data_V_1_vld_out = dout_words_V_data_V_1_state.read()[0];
}

void datag::thread_dout_words_V_tlast_1_ack_in() {
    dout_words_V_tlast_1_ack_in = dout_words_V_tlast_1_state.read()[1];
}

void datag::thread_dout_words_V_tlast_1_ack_out() {
    dout_words_V_tlast_1_ack_out = dout_words_TREADY.read();
}

void datag::thread_dout_words_V_tlast_1_data_out() {
    dout_words_V_tlast_1_data_out =  (sc_logic) (ap_const_lv1_1[0]);
}

void datag::thread_dout_words_V_tlast_1_sel() {
    dout_words_V_tlast_1_sel = dout_words_V_tlast_1_sel_rd.read();
}

void datag::thread_dout_words_V_tlast_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        dout_words_V_tlast_1_vld_in = ap_const_logic_1;
    } else {
        dout_words_V_tlast_1_vld_in = ap_const_logic_0;
    }
}

void datag::thread_dout_words_V_tlast_1_vld_out() {
    dout_words_V_tlast_1_vld_out = dout_words_V_tlast_1_state.read()[0];
}

void datag::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_state.read()[0]) && esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_state.read()[0]) && esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_state.read()[0]) && esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_state.read()[0]) && esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_state.read()[0]) && esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_state.read()[0]) && esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_state.read()[0]) && !(esl_seteq<1,1,1>(ap_const_logic_0, control_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_V_data_V_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, din_words_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dout_words_V_tlast_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

void datag::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"din_TDATA\" :  \"" << din_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"din_TVALID\" :  \"" << din_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"din_TREADY\" :  \"" << din_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"din_TLAST\" :  \"" << din_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"control_V_TDATA\" :  \"" << control_V_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"control_V_TVALID\" :  \"" << control_V_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"control_V_TREADY\" :  \"" << control_V_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"din_words_TDATA\" :  \"" << din_words_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"din_words_TVALID\" :  \"" << din_words_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"din_words_TREADY\" :  \"" << din_words_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"din_words_TLAST\" :  \"" << din_words_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dout_words_TDATA\" :  \"" << dout_words_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dout_words_TVALID\" :  \"" << dout_words_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dout_words_TREADY\" :  \"" << dout_words_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dout_words_TLAST\" :  \"" << dout_words_TLAST.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

